### ISSUE TITLE
schematics should be different?

### ISSUE THREAD

**Issue by irdispsyhonikum** [AghostPrj/Radxa-emmc-module#1]
Hello. 

Sorry for bothering you, but I beleive schematics should be different than the Radxa itself.
Just if to follow all as on your schematics, then pins will be connected upperwise. 
I might be wrong. I am not professional, but all looks like that.

![emmc_schematics](https://github.com/AghostPrj/Radxa-emmc-module/assets/12295303/1b1cf576-259a-44b9-8159-f2e98da70828)

Kind regards
Jrijs

**Comment by irdispsyhonikum** [comment]
Sorry. I am really unprovessional in this case. Tryed similar and all looks like it should be.

**Comment by ggg17226** [comment]
this circuit has been tested and works well
tested board by myself: orangepi 5plus/radxa rock 3a/radxa rock 5a/radxa rock 5b
